# Generated by Django 4.1.3 on 2022-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
